Split InitializeKeycloakConfig and add KeycloakContainerTest
1. Introduce a dependency on the Keycloak testcontainers project
  * Note: this depends on a yet-to-be-released SNAPSHOT version of
https://github.com/dasniko/testcontainers-keycloak
2. Split InitializeKeycloakConfig into a Main and a Configurator; this
should make it easier to use the configurator from the new test
3. Introduce a placeholder test that
  * Uses the testcontainers-keycloak project to launch a keycloak
container from the JUnit
  * Uses the keycloak-config project to configure the container with a
test tenant
  * Retrieves the server info
4. Add the `jboss-deployment-structure.xml` back in. I wasn't sure if it
was needed or not but without it I'm seeing
"java.lang.NoClassDefFoundError: Failed to link" errors while
initializing the test realm with a PatientPrefixUserAttributeMapper.